// Code generated by sfgenx. DO NOT EDIT.

package squery

import (
	"encoding/json"
)

// known values in JSON
var (
	vNull  = []byte("null")
	vTrue  = []byte("true")
	vFalse = []byte("false")
)

// value type of the node
type valueType int

// known value types
const (
	tUnknown valueType = iota
	tNull
	tBoolean
	tNumber
	tString
	tOperator
	tArray
	tArrayBetween
)

// String interface
func (v valueType) String() string {
	switch v {
	case tNull:
		return "null"
	case tBoolean:
		return "bool"
	case tNumber:
		return "number"
	case tString:
		return "string"
	case tOperator:
		return "operator"
	case tArray, tArrayBetween:
		return "array"
	default:
		return "unknown"
	}
}
func (v valueType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.String())
}
